Add a few commands for working with the data layout.
dkfellows/llvmtcl pull request #17
Opened 2018-04-24 03:34 UTC by kennykb

Describe what your Pull Request is implementing
-----------------------------------------------

In order to implement 'sizeof' and 'alignof' correctly, and to get the LLVM coroutine frame built correctly, I needed to add interfaces to a few of the LLVM API's for working with target machines.

Version number advanced to 3.10.0 for the new interfaces.

Describe the platform you are using
-----------------------------------

Ubuntu 17.10, LLVM 5.0 from system package manager, Tcl 8..7 built from core-8-branch

2018-04-27 06:18 UTC, dkfellows requested changes
One nasty bug left.

2018-04-27 06:18 UTC, dkfellows commented on generic/llvmtcl.cpp
> +	Tcl_WrongNumArgs(interp, 1, objv, "?Target?");
Missing `return TCL_ERROR`

2018-04-28 09:51 UTC, dkfellows commented
I'm hoping I can get this into the 3.9 release, which I want to get out in the next couple of days.

2018-04-28 10:52 UTC, dkfellows commented
https://github.com/dkfellows/llvmtcl/tree/kbk/target-data has my fixes.

2018-04-28 15:01 UTC, kennykb commented
Thanks, Donal, for tidying up after me.  Right now the coroutine changes simply have too many moving parts and I'm leaving a bit of a mess wherever I go.

2018-04-28 15:01 UTC, closed without merging